version: 2
jobs:
  deploy:
    machine: true
    steps:
      - checkout
      - run:
          name: "conoha deploy"
          command: ssh -A -o StrictHostKeyChecking=no /home/kusanagi/html/DocumentRoot/wp-content/themes/forestone_corp/config/deploy.sh

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
