version: 2
jobs:
  deploy:
    machine: true
    steps:
      - checkout
      - run:
          name: "conoha deploy"
          command: ssh -A -o root@133.130.101.97 StrictHostKeyChecking=no IdentitiesOnly=yes AddKeysToAgent=yes UseKeychain=yes TCPKeepAlive=yes Compression=yes GSSAPIAuthentication=no UseRoaming=no

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
