version: 2
jobs:
  deploy:
    machine: true
    steps:
      - checkout
      - run:
          name: "conoha deploy"
          command: ssh -A -o StrictHostKeyChecking=no root@133.130.101.97

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
